// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnXJs--OERI9AEGQQeSF8eop8nmDiYtbA',
    appId: '1:973340214263:web:25caaa9b722cd24fa0e4f2',
    messagingSenderId: '973340214263',
    projectId: 'bucketlistwithfirebase-e3efc',
    authDomain: 'bucketlistwithfirebase-e3efc.firebaseapp.com',
    storageBucket: 'bucketlistwithfirebase-e3efc.appspot.com',
    measurementId: 'G-FTBJFZTY2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tGMYrkzFMj1B7TnTrzszFI85tu6PlJQ',
    appId: '1:973340214263:android:9d989aa7e28f8cd9a0e4f2',
    messagingSenderId: '973340214263',
    projectId: 'bucketlistwithfirebase-e3efc',
    storageBucket: 'bucketlistwithfirebase-e3efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbrTeKe-S4nI0qOytYUNL3geY6DdFl6pg',
    appId: '1:973340214263:ios:cb41fe53131c9b1da0e4f2',
    messagingSenderId: '973340214263',
    projectId: 'bucketlistwithfirebase-e3efc',
    storageBucket: 'bucketlistwithfirebase-e3efc.appspot.com',
    iosClientId: '973340214263-f529377396511n1o5qjbpgcdmuiqmg19.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbrTeKe-S4nI0qOytYUNL3geY6DdFl6pg',
    appId: '1:973340214263:ios:cb41fe53131c9b1da0e4f2',
    messagingSenderId: '973340214263',
    projectId: 'bucketlistwithfirebase-e3efc',
    storageBucket: 'bucketlistwithfirebase-e3efc.appspot.com',
    iosClientId: '973340214263-f529377396511n1o5qjbpgcdmuiqmg19.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucketListWithFirebase',
  );
}
